# Generated by Django 4.0 on 2022-01-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_contenido_post_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
